## Main Ingress
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: ingress
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/proxy-body-size: 100m
#    nginx.ingress.kubernetes.io/use-regex: "true"
#spec:
#  rules:
#    - host: api.holamind.xyz
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: django-service
#              servicePort: 8000
#    - host: flower.holamind.xyz
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: flower-service
#              servicePort: 5555
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: my-ingress
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /*
#        backend:
#          serviceName: my-products
#          servicePort: 60000
#      - path: /discounted
#        backend:
#          serviceName: my-discounted-products
#          servicePort: 80

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: django-service # this need to be either NodePort or LoadBalancer
          servicePort: 8000
      - path: /flower
        backend:
          serviceName: flower-service # this need to be either NodePort or LoadBalancer
          servicePort: 5555
