apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: umeshvjti/fakeimage:latest
          command: ["/bin/sh"]
          args: [ "-c", "python manage.py migrate --noinput"]
          envFrom:
          - configMapRef:
              name: appconfig
          - secretRef:
              name: appsecrets
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: django-collectstatic
spec:
  template:
    spec:
      containers:
        - name: collectstatic
          image: umeshvjti/fakeimage:latest
          command: ["/bin/sh"]
          args: [ "-c", "python manage.py collectstatic --noinput"]
          envFrom:
          - configMapRef:
              name: appconfig
          - secretRef:
              name: appsecrets
      restartPolicy: Never

