apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
type: Opaque
data:
  DJANGO_SECRET_KEY: dTV4K2w2bTAoc2k0Nz1wNyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  TWILLIO_AUTH_TOKEN: YWJhMzQxMjkwNmVhNGZlM2M1OTExZjc4ZDQ0ODhiNTQ=
  TWILLIO_ACCOUNT_SID: QUM4NzY3OGM1ZTE1MDgyMWFjYjkxNjAyZjc5OWYxNWRhYQ==
  TWILLIO_API_KEY_SID: U0syMjU5YzFkOTM5NTlhZGExOGE1MGU1Y2JmODM3ODBmNw==
  TWILLIO_API_KEY_SECRET: ME04UDdlNGxUdWdEV3B3MUN1czd0bXRodHdONW9pbmo=
  MAILGUN_API_KEY: YTY1MTczYjEtNDg3NTAzNDA=
  EMAIL_HOST_PASSWORD: YjJiMzgxZTQ1ZWY0MTA3NDc4ZjQ0NDM2NDlkOWE4ODMtYTY1MTczYjEtMzBlYzUxZWM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
