apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
#          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          image: umeshvjti/holaskills:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: [ "-c", "python manage.py migrate --noinput"]
          envFrom:
          - configMapRef:
              name: appconfig
          - secretRef:
              name: appsecrets
      restartPolicy: Never
#      activeDeadlineSeconds: 100
      imagePullSecrets:
      - name: regcred
